baseURL = 'https://kvazistam.github.io/portfolio/'
languageCode = 'en-us'
title = 'Портфолио Маковеева Никиты Владимировича'
theme = 'paper'

[params]
  github = "kvazistam"
  name = "kvazistam"


[menu]
  [[menu.main]]
    name = "Курсы"
    url = "/courses/"
    weight = 10